-- CREAZIONE DATABASE
DROP DATABASE IF EXISTS db_no_pawblems;
CREATE DATABASE db_no_pawblems;
USE db_no_pawblems;

-- CREAZIONE TABELLE
CREATE TABLE UTENTE(
	ID_UTENTE INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    COGNOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    TELEFONO VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(64) NOT NULL,
	ADMIN BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE INDIRIZZO(
	ID_INDIRIZZO INTEGER AUTO_INCREMENT PRIMARY KEY,
    UTENTE INTEGER,
    VIA VARCHAR(100) NOT NULL,
    CITTA VARCHAR(50) NOT NULL,
    CAP VARCHAR(5) NOT NULL,
    PROVINCIA VARCHAR(5) NOT NULL,                  
    NAZIONE VARCHAR(50) NOT NULL, 

    CONSTRAINT FK_UTENTE_INDIRIZZO FOREIGN KEY (UTENTE) REFERENCES UTENTE(ID_UTENTE) ON DELETE SET NULL
);

CREATE TABLE CATEGORIA(
	ID_CATEGORIA INTEGER AUTO_INCREMENT PRIMARY KEY,
    ID_PADRE INTEGER NULL,
    NOME VARCHAR(50) NOT NULL UNIQUE,
    DESCRIZIONE TEXT NULL,
    
    CONSTRAINT FK_CATEGORIA_PADRE FOREIGN KEY (ID_PADRE) REFERENCES CATEGORIA(ID_CATEGORIA) ON DELETE CASCADE
);

CREATE TABLE PRODOTTO(
	ID_PRODOTTO INTEGER AUTO_INCREMENT PRIMARY KEY,
    CATEGORIA INTEGER NOT NULL,
    NOME VARCHAR(150) NOT NULL,
    DESCRIZIONE TEXT NOT NULL,
    TAGLIA VARCHAR(5) NOT NULL,
    COLORE VARCHAR(20) NOT NULL,
    PREZZO DECIMAL(10,2) NOT NULL,       
    IVA INTEGER NOT NULL DEFAULT 22,                 
    DISPONIBILITA INTEGER NOT NULL DEFAULT 0,
    ATTIVO BOOLEAN NOT NULL DEFAULT TRUE,
    
    CONSTRAINT FK_CATEGORIA_PRODOTTO FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA) ON UPDATE CASCADE
);

CREATE TABLE IMMAGINE(
	ID_IMMAGINE INTEGER AUTO_INCREMENT PRIMARY KEY,
    PRODOTTO INTEGER NOT NULL, 
    URL VARCHAR(255) NOT NULL, 
    ALT VARCHAR(50) NOT NULL,
    
    CONSTRAINT FK_PRODOTTO_IMMAGINE FOREIGN KEY (PRODOTTO) REFERENCES PRODOTTO(ID_PRODOTTO) ON DELETE CASCADE
);

CREATE TABLE ORDINE(
	ID_ORDINE INTEGER AUTO_INCREMENT PRIMARY KEY,
    UTENTE INTEGER,
    VIA_SPEDIZIONE VARCHAR(100) NOT NULL,
    CITTA_SPEDIZIONE VARCHAR(50) NOT NULL,
    CAP_SPEDIZIONE VARCHAR(5) NOT NULL,
    PROVINCIA_SPEDIZIONE VARCHAR(5) NOT NULL,                  
    NAZIONE_SPEDIZIONE VARCHAR(50) NOT NULL, 
    DATA_ORDINE DATETIME NOT NULL,
    STATO VARCHAR(20) NOT NULL DEFAULT "In Elaborazione",
    TOTALE DECIMAL(10, 2) NOT NULL,
    NUMERO_FATTURA VARCHAR(20) NULL,
	
    CONSTRAINT FK_UTENTE_ORDINE FOREIGN KEY (UTENTE) REFERENCES UTENTE(ID_UTENTE) ON DELETE SET NULL
);

CREATE TABLE DETTAGLIO_ORDINE(
	ID_DETTAGLIO_ORDINE INTEGER AUTO_INCREMENT PRIMARY KEY,
	ORDINE INTEGER NOT NULL,
    PRODOTTO INTEGER NOT NULL,
	QUANTITA INTEGER NOT NULL,
    PREZZO_ACQUISTO DECIMAL(10,2) NOT NULL,    
    IVA_ACQUISTO INTEGER NOT NULL,                 

	CONSTRAINT UQ_ORDINE_PRODOTTO UNIQUE (ORDINE, PRODOTTO),
    CONSTRAINT FK_ORDINE_DETTAGLIO_ORDINE FOREIGN KEY (ORDINE) REFERENCES ORDINE(ID_ORDINE) ON DELETE CASCADE,
    CONSTRAINT FK_PRODOTTO_DETTAGLIO_ORDINE FOREIGN KEY (PRODOTTO) REFERENCES PRODOTTO(ID_PRODOTTO) ON DELETE RESTRICT 
);

-- POPOLAMENTO DATABASE
INSERT INTO CATEGORIA (ID_PADRE, NOME, DESCRIZIONE) 
VALUES (NULL, 'Cani', 'Tutto il necessario per il tuo cane');
INSERT INTO CATEGORIA (ID_PADRE, NOME, DESCRIZIONE) 
VALUES (NULL, 'Gatti', 'Tutto il necessario per il tuo gatto');

-- POPOLAMENTO UTENTI (Password fittizie in SHA-256 o testo semplice per il test)
INSERT INTO UTENTE (NOME, COGNOME, EMAIL, TELEFONO, PASSWORD, ADMIN) VALUES 
('Mario', 'Rossi', 'mario.rossi@email.com', '3331234567', 'ef92b778bafe421548577089b2ee2892', FALSE),
('Anna', 'Verdi', 'anna.verdi@email.com', '3449876543', 'c77458e8e4aa2212445e9bb212e21111', TRUE);

-- POPOLAMENTO INDIRIZZI (Collegati a Mario Rossi, ID_UTENTE = 1)
INSERT INTO INDIRIZZO (UTENTE, VIA, CITTA, CAP, PROVINCIA, NAZIONE) VALUES 
(1, 'Via Roma 10', 'Napoli', '80100', 'NA', 'Italia'),
(1, 'Corso Umberto I 45', 'Milano', '20100', 'MI', 'Italia');

-- POPOLAMENTO PRODOTTI (Collegati alle categorie 1 = Cani, 2 = Gatti)
INSERT INTO PRODOTTO (CATEGORIA, NOME, DESCRIZIONE, TAGLIA, COLORE, PREZZO, IVA, DISPONIBILITA, ATTIVO) VALUES 
(1, 'Collare Antiparassitario', 'Protezione totale fino a 8 mesi', 'M', 'Grigio', 35.90, 22, 50, TRUE),
(2, 'Tiragraffi a Torre', 'Albero tiragraffi con morbida cuccia', 'XL', 'Beige', 49.99, 22, 12, TRUE);

-- POPOLAMENTO IMMAGINI (ID_PRODOTTO 1 e 2)
INSERT INTO IMMAGINE (PRODOTTO, URL, ALT) VALUES 
(1, 'images/prodotti/collare_cani.jpg', 'Collare antiparassitario per cani di taglia media'),
(2, 'images/prodotti/tiragraffi_gatti.jpg', 'Albero tiragraffi spazioso per gatti');

-- POPOLAMENTO ORDINI (Effettuato da Mario Rossi ID = 1)
INSERT INTO ORDINE (UTENTE, VIA_SPEDIZIONE, CITTA_SPEDIZIONE, CAP_SPEDIZIONE, PROVINCIA_SPEDIZIONE, NAZIONE_SPEDIZIONE, DATA_ORDINE, STATO, TOTALE, NUMERO_FATTURA) VALUES 
(1, 'Via Roma 10', 'Napoli', '80100', 'NA', 'Italia', NOW(), 'In Elaborazione', 85.89, 'FAT-2026-0001');

-- POPOLAMENTO DETTAGLIO ORDINE (L''ordine precedente contiene entrambi i prodotti)
INSERT INTO DETTAGLIO_ORDINE (ORDINE, PRODOTTO, QUANTITA, PREZZO_ACQUISTO, IVA_ACQUISTO) VALUES 
(1, 1, 1, 35.90, 22), -- 1 Collare
(1, 2, 1, 49.99, 22); -- 1 Tiragraffim