-- CREAZIONE DATABASE
DROP DATABASE IF EXISTS db_no_pawblems;
CREATE DATABASE db_no_pawblems;
USE db_no_pawblems;

-- CREAZIONE TABELLE
CREATE TABLE UTENTE(
	ID_UTENTE INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    COGNOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    TELEFONO VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(64) NOT NULL,
	ADMIN BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE INDIRIZZO(
	ID_INDIRIZZO INTEGER AUTO_INCREMENT PRIMARY KEY,
    UTENTE INTEGER,
    VIA VARCHAR(100) NOT NULL,
    CITTA VARCHAR(50) NOT NULL,
    CAP VARCHAR(5) NOT NULL,
    PROVINCIA VARCHAR(5) NOT NULL,                  
    NAZIONE VARCHAR(50) NOT NULL, 

    CONSTRAINT FK_UTENTE_INDIRIZZO FOREIGN KEY (UTENTE) REFERENCES UTENTE(ID_UTENTE) ON DELETE SET NULL
);

CREATE TABLE CATEGORIA(
	ID_CATEGORIA INTEGER AUTO_INCREMENT PRIMARY KEY,
    ID_PADRE INTEGER NULL,
    NOME VARCHAR(50) NOT NULL UNIQUE,
    DESCRIZIONE TEXT NULL,
    
    CONSTRAINT FK_CATEGORIA_PADRE FOREIGN KEY (ID_PADRE) REFERENCES CATEGORIA(ID_CATEGORIA) ON DELETE CASCADE
);

CREATE TABLE PRODOTTO(
    ID_PRODOTTO INTEGER AUTO_INCREMENT PRIMARY KEY,
    CATEGORIA INTEGER NOT NULL,
    NOME VARCHAR(150) NOT NULL,
    DESCRIZIONE TEXT NOT NULL,
    ATTIVO BOOLEAN NOT NULL DEFAULT TRUE, 
    
    CONSTRAINT FK_CATEGORIA_PRODOTTO FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA) ON UPDATE CASCADE
);

CREATE TABLE VARIANTE_PRODOTTO(
    ID_VARIANTE INTEGER AUTO_INCREMENT PRIMARY KEY,
    PRODOTTO_PADRE INTEGER NOT NULL, 
    TAGLIA VARCHAR(10) NOT NULL,    
    COLORE VARCHAR(30) NOT NULL,
    COLORE_HEX VARCHAR(7) NULL,
    PREZZO DECIMAL(10,2) NOT NULL,       
    IVA INTEGER NOT NULL DEFAULT 22,                 
    DISPONIBILITA INTEGER NOT NULL DEFAULT 0,
    
    CONSTRAINT FK_PRODOTTO_VARIANTE FOREIGN KEY (PRODOTTO_PADRE) REFERENCES PRODOTTO(ID_PRODOTTO) ON DELETE CASCADE
);

CREATE TABLE IMMAGINE(
	ID_IMMAGINE INTEGER AUTO_INCREMENT PRIMARY KEY,
    PRODOTTO INTEGER NOT NULL, 
    URL VARCHAR(255) NOT NULL, 
    ALT VARCHAR(50) NOT NULL,
    
    CONSTRAINT FK_PRODOTTO_IMMAGINE FOREIGN KEY (PRODOTTO) REFERENCES PRODOTTO(ID_PRODOTTO) ON DELETE CASCADE
);

CREATE TABLE ORDINE(
	ID_ORDINE INTEGER AUTO_INCREMENT PRIMARY KEY,
    UTENTE INTEGER,
    VIA_SPEDIZIONE VARCHAR(100) NOT NULL,
    CITTA_SPEDIZIONE VARCHAR(50) NOT NULL,
    CAP_SPEDIZIONE VARCHAR(5) NOT NULL,
    PROVINCIA_SPEDIZIONE VARCHAR(5) NOT NULL,                  
    NAZIONE_SPEDIZIONE VARCHAR(50) NOT NULL, 
    DATA_ORDINE DATETIME NOT NULL,
    STATO VARCHAR(20) NOT NULL DEFAULT "In Elaborazione",
    TOTALE DECIMAL(10, 2) NOT NULL,
    NUMERO_FATTURA VARCHAR(20) NULL,
	
    CONSTRAINT FK_UTENTE_ORDINE FOREIGN KEY (UTENTE) REFERENCES UTENTE(ID_UTENTE) ON DELETE SET NULL
);

CREATE TABLE DETTAGLIO_ORDINE(
    ID_DETTAGLIO_ORDINE INTEGER AUTO_INCREMENT PRIMARY KEY,
    ORDINE INTEGER NOT NULL,
    VARIANTE INTEGER NOT NULL,
    QUANTITA INTEGER NOT NULL,
    PREZZO_ACQUISTO DECIMAL(10,2) NOT NULL,    
    IVA_ACQUISTO INTEGER NOT NULL,                 

    CONSTRAINT UQ_ORDINE_VARIANTE UNIQUE (ORDINE, VARIANTE),
    CONSTRAINT FK_ORDINE_DETTAGLIO_ORDINE FOREIGN KEY (ORDINE) REFERENCES ORDINE(ID_ORDINE) ON DELETE CASCADE,
    CONSTRAINT FK_VARIANTE_DETTAGLIO_ORDINE FOREIGN KEY (VARIANTE) REFERENCES VARIANTE_PRODOTTO(ID_VARIANTE) ON DELETE RESTRICT 
);

CREATE TABLE PRODOTTO_CARRELLO(
    UTENTE INTEGER NOT NULL,
    VARIANTE INTEGER NOT NULL, 
    QUANTITA INTEGER NOT NULL DEFAULT 1,
    
    CONSTRAINT PK_CARRELLO PRIMARY KEY (UTENTE, VARIANTE),
    CONSTRAINT FK_UTENTE_CARRELLO FOREIGN KEY (UTENTE) REFERENCES UTENTE(ID_UTENTE) ON DELETE CASCADE,
    CONSTRAINT FK_VARIANTE_CARRELLO FOREIGN KEY (VARIANTE) REFERENCES VARIANTE_PRODOTTO(ID_VARIANTE) ON DELETE CASCADE
);

-- POPOLAMENTO DATABASE
-- POPOLAMENTO DI ESEMPIO PER CAPIRNE LA LOGICA
INSERT INTO CATEGORIA (ID_PADRE, NOME, DESCRIZIONE) VALUES (NULL, 'Cani', 'Tutto per il tuo cane');

-- Inseriamo un Prodotto Padre (Master)
INSERT INTO PRODOTTO (CATEGORIA, NOME, DESCRIZIONE) 
VALUES (1, 'Collare Comfort Nylon', 'Un fantastico collare ultra resistente per cani di ogni taglia.');

-- Inseriamo le sue varianti (Detail) legate al Padre con ID 1
-- Variante 1: Taglia S, Colore Rosso (con relativo codice HEX)
INSERT INTO VARIANTE_PRODOTTO (PRODOTTO_PADRE, TAGLIA, COLORE, COLORE_HEX, PREZZO, DISPONIBILITA) 
VALUES (1, 'S', 'Rosso', '#FF0000', 12.50, 15);

-- Variante 2: Taglia M, Colore Rosso
INSERT INTO VARIANTE_PRODOTTO (PRODOTTO_PADRE, TAGLIA, COLORE, COLORE_HEX, PREZZO, DISPONIBILITA) 
VALUES (1, 'M', 'Rosso', '#FF0000', 15.00, 10);

-- Variante 3: Taglia M, Colore Blu
INSERT INTO VARIANTE_PRODOTTO (PRODOTTO_PADRE, TAGLIA, COLORE, COLORE_HEX, PREZZO, DISPONIBILITA) 
VALUES (1, 'M', 'Blu', '#0000FF', 15.00, 8);